version: 3

services:
    app:
        image: gitea/gitea:latest
        container_name: gitea-aatman
        restart: always
        ports:
            - 8081:3000
            - 2222:2222
        volumes:
            - /trayimurti/containers/volumes/gitea/root/data:/var/lib/gitea
            - /trayimurti/containers/volumes/gitea/root/config:/etc/gitea
#            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ROOT_URL=http://0.pi:8081
            - GITEA__database__DB_TYPE=postgres
            - GITEA__database__HOST=db:5432
            - GITEA__database__NAME=gitea
            - GITEA__database__USER=gitea
            - GITEA__database__PASSWD=/run/secrets/postgres_user_passwd
#            - GITEA__database__PASSWD=gitea
            - TZ=Asia/Kolkata
        security_opt:
            - label=disable
        depends_on:
            - db
        secrets:
            - postgres_user_passwd

    db:
        image: postgres:alpine
        container_name: gitea-dhyana
        restart: always
        volumes:
            - /trayimurti/containers/volumes/gitea/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=gitea
            - POSTGRES_PASSWORD=/run/secrets/postgres_user_passwd
#            - POSTGRES_PASSWORD=gitea
            - POSTGRES_DB=gitea
            - TZ=Asia/Kolkata
        secrets:
            - postgres_user_passwd
        security_opt:
            - label=disable

secrets:
    postgres_user_passwd:
        external: true

# create dirs
# mkdir -vp /trayimurti/containers/volumes/gitea/{db,root/{data,config}}

# create secrets
# openssl rand -base64 20 | podman secret create postgres_user_passwd -
