version: 3

services:
    app:
        image: gitea/gitea:latest
        container_name: gitea-govinda
        restart: always
        ports:
            - 8020:3000
            - 8021:2222
        volumes:
            - /trayimurti/containers/volumes/gitea/root/data:/var/lib/gitea:Z
            - /trayimurti/containers/volumes/gitea/root/config:/etc/gitea:Z
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ROOT_URL=https://git.thefossguy.com
            - GITEA__database__DB_TYPE=postgres
            - GITEA__database__HOST=db:5432
            - GITEA__database__NAME=gitea
            - GITEA__database__USER=gitea
            - GITEA__database__PASSWD=/run/secrets/gitea_database_user_password
            - TZ=Asia/Kolkata
        depends_on:
            - db
        secrets:
            - gitea_database_user_password

    db:
        image: postgres:alpine
        container_name: gitea-chitragupta
        restart: always
        volumes:
            - /trayimurti/containers/volumes/gitea/db:/var/lib/postgresql/data:Z
        environment:
            - POSTGRES_USER=gitea
            - POSTGRES_PASSWORD=/run/secrets/gitea_database_user_password
            - POSTGRES_DB=gitea
            - TZ=Asia/Kolkata
        secrets:
            - gitea_database_user_password

secrets:
    gitea_database_user_password:
        external: true

# create dirs
# mkdir -vp /trayimurti/containers/volumes/gitea/{db,root/{data,config}}

# create secrets
# openssl rand -base64 20 | podman secret create gitea_database_user_password -
