version: 3.7

services:


    reverse-proxy:
        image: caddy:alpine
        container_name: caddy-vishwambhar
        command: caddy run --config /etc/caddy/Caddyfile
        restart: always
        ports:
            - "8080:80"
            - "8443:443"
        volumes:
            - /trayimurti/containers/volumes/caddy/Caddyfile:/etc/caddy/Caddyfile:Z
            - /trayimurti/containers/volumes/caddy/site:/srv:Z
            - /trayimurti/containers/volumes/caddy/caddy_data:/data:Z
            - /trayimurti/containers/volumes/caddy/caddy_config:/config:Z
            - /trayimurti/containers/volumes/caddy/ssl:/etc/ssl:Z
        labels:
            - io.containers.autoupdate=registry
            - pratham.container.category=proxy
        environment:
            - TZ=Asia/Kolkata
        depends_on:
            - gitea-web
            - thefossguy-blog
            - nextcloud-web
            - thefossguy-mach
            - transmission-raadhe


    gitea-web:
        image: gitea/gitea:latest
        container_name: gitea-govinda
        restart: always
        ports:
            - "8010:3000"
            - "8011:22"
        volumes:
            - /trayimurti/containers/volumes/gitea/web:/data:Z
            - /trayimurti/containers/volumes/gitea/ssh:/data/git/.ssh:Z
#            - /trayimurti/containers/volumes/gitea/web/data:/var/lib/gitea:Z
#            - /trayimurti/containers/volumes/gitea/web/config:/etc/gitea:Z
            - /etc/localtime:/etc/localtime:ro
        labels:
            - io.containers.autoupdate=registry
            - pratham.container.category=gitea
        environment:
            - DEFAULT_BRANCH=master
            - RUN_MODE=prod
            - DISABLE_SSH=false
            - START_SSH_SERVER=true
            - SSH_PORT=22
            - SSH_LISTEN_PORT=22
            - ROOT_URL=https://git.thefossguy.com
            - DOMAIN=git.thefossguy.com
            - SSH_DOMAIN=git.thefossguy.com
            - GITEA__database__DB_TYPE=postgres
            - GITEA__database__HOST=gitea-db:5432
            - GITEA__database__NAME=gitea
            - GITEA__database__USER=gitea
            - GITEA__database__PASSWD=/run/secrets/gitea_database_user_password
            - GITEA__service__DISABLE_REGISTRATION=true
            - TZ=Asia/Kolkata
        depends_on:
            - gitea-db
        secrets:
            - gitea_database_user_password


    gitea-db:
        image: postgres:alpine
        container_name: gitea-chitragupta
        restart: always
        volumes:
            - /trayimurti/containers/volumes/gitea/database:/var/lib/postgresql/data:Z
        labels:
            - io.containers.autoupdate=registry
            - pratham.container.category=gitea
        environment:
            - POSTGRES_USER=gitea
            - POSTGRES_PASSWORD=/run/secrets/gitea_database_user_password
            - POSTGRES_DB=gitea
            - TZ=Asia/Kolkata
        secrets:
            - gitea_database_user_password


    thefossguy-blog:
        image: klakegg/hugo:alpine
        container_name: hugo-vaikunthnatham
        command: server --disableFastRender -b https://blog.thefossguy.com/ --appendPort=false
        restart: always
        ports:
            - "8020:1313"
        volumes:
            - /trayimurti/containers/volumes/blog:/src:Z
        labels:
            - io.containers.autoupdate=registry
            - pratham.container.category=blog
        environment:
            - TZ=Asia/Kolkata


    nextcloud-web:
        image: nextcloud:production
        container_name: nextcloud-govinda
        restart: always
        ports:
            - "8030:80"
        volumes:
            - /trayimurti/containers/volumes/nextcloud/web:/var/www/html:z
        labels:
            - io.containers.autoupdate=registry
            - pratham.container.category=cloud
        environment:
            - POSTGRES_PASSWORD=/run/secrets/nextcloud_database_user_password
            - POSTGRES_DB=nextcloud
            - POSTGRES_USER=nextcloud
            - POSTGRES_HOST=nextcloud-db
            - NEXTCLOUD_TRUSTED_DOMAINS=cloud.thefossguy.com
            - OVERWRITECLIURL=https://cloud.thefossguy.com
            - OVERWRITEPROTOCOL=https
            - TZ=Asia/Kolkata
        depends_on:
            - nextcloud-db
        secrets:
            - nextcloud_database_user_password


    nextcloud-db:
        image: postgres:alpine
        container_name: nextcloud-chitragupta
        restart: always
        volumes:
            - /trayimurti/containers/volumes/nextcloud/database:/var/lib/postgresql/data:Z
        labels:
            - io.containers.autoupdate=registry
            - pratham.container.category=cloud
        environment:
            - POSTGRES_DB=nextcloud
            - POSTGRES_USER=nextcloud
            - POSTGRES_PASSWORD=/run/secrets/nextcloud_database_user_password
            - TZ=Asia/Kolkata
        secrets:
            - nextcloud_database_user_password


    nextcloud-cron:
        image: nextcloud:production
        container_name: nextcloud-karma
        entrypoint: /cron.sh
        restart: always
        volumes:
            - /trayimurti/containers/volumes/nextcloud/web:/var/www/html:z
        labels:
            - io.containers.autoupdate=registry
            - pratham.container.category=cloud
        environment:
            - TZ=Asia/Kolkata
        depends_on:
            - nextcloud-web
            - nextcloud-db


    thefossguy-mach:
        image: klakegg/hugo:alpine
        container_name: hugo-mahayogi
        command: server --disableFastRender -b https://mach.thefossguy.com/ --appendPort=false
        restart: always
        ports:
            - "8040:1313"
        volumes:
            - /trayimurti/containers/volumes/mach:/src:Z
        labels:
            - io.containers.autoupdate=registry
            - pratham.container.category=mach
        environment:
            - TZ=Asia/Kolkata


    wireguard-client:
        image: lscr.io/linuxserver/wireguard:latest
        container_name: wireguard-shyaam
        restart: always
        ports:
            - "8050:9091"           # transmission web-ui
            - "8051:51413"          # transmission; idk what
            - "8052:51413/udp"      # transmission; idk what
            - "8053:51820/udp"      # wireguard
        volumes:
            - /trayimurti/torrents/wg-conf:/config:Z
            - /lib/modules:/lib/modules:ro
        labels:
            - io.containers.autoupdate=registry
            - pratham.container.category=torrent
        environment:
#            - SERVERURL=auto    # determine and set external IP automatically
#            - SERVERPORT=51820
            - TZ=Asia/Kolkata
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        networks:
            - network-torr
            - container-compose_default


    transmission-web:
        image: lscr.io/linuxserver/transmission:latest
        container_name: transmission-raadhe
        restart: always
        volumes:
            - /trayimurti/torrents/downloads:/downloads:Z
            - /trayimurti/torrents/config:/config:Z
        labels:
            - io.containers.autoupdate=registry
            - pratham.container.category=torrent
        environment:
            - TZ=Asia/Kolkata
        depends_on:
            - wireguard-client
#        network_mode: 'service:wireguard-shyaam'
        networks:
            - network-torr
            - container-compose_default


secrets:
    gitea_database_user_password:
        external: true
    nextcloud_database_user_password:
        external: true


networks:
    network-torr:
    container-compose_default:
        external:
            true

# SERVICE_TEMPLATE
#    service:
#        image: 
#        container_name: 
#        command OR entrypoint:
#        restart: always
#        ports:
#        volumes:
#        labels:
#            - io.containers.autoupdate=registry
#            - pratham.container.category=
#        environment:
#            - TZ=Asia/Kolkata
#        sysctls:
#        cap_add:
#        depends_on:
#        secrets:
#        networks:
