version: 3.7

services:

    reverse-proxy:
        image: caddy:2-alpine
        container_name: caddy-vishwakarma
        command: caddy run --config /etc/caddy/Caddyfile
        restart: always
        ports:
            - 8080:80
            - 8443:443
        volumes:
            - /trayimurti/containers/volumes/caddy/Caddyfile:/etc/caddy/Caddyfile:Z
            - /trayimurti/containers/volumes/caddy/site:/srv:Z
            - /trayimurti/containers/volumes/caddy/caddy_data:/data:Z
            - /trayimurti/containers/volumes/caddy/caddy_config:/config:Z
            - /trayimurti/containers/volumes/caddy/ssl:/etc/ssl:Z
        depends_on:
            - gitea-web
            - nextcloud-web
            - thefossguy-blog
            - thefossguy-mach

    gitea-web:
        image: gitea/gitea:latest
        container_name: gitea-govinda
        restart: always
        ports:
            - 8010:3000
            - 8011:2222
        volumes:
            - /trayimurti/containers/volumes/gitea/root/data:/var/lib/gitea:Z
            - /trayimurti/containers/volumes/gitea/root/config:/etc/gitea:Z
            - /etc/localtime:/etc/localtime:ro
        environment:
            - ROOT_URL=https://git.thefossguy.com
            - GITEA__database__DB_TYPE=postgres
            - GITEA__database__HOST=db:5432
            - GITEA__database__NAME=gitea
            - GITEA__database__USER=gitea
            - GITEA__database__PASSWD=/run/secrets/gitea_database_user_password
            - TZ=Asia/Kolkata
        depends_on:
            - gitea-db
        secrets:
            - gitea_database_user_password

    gitea-db:
        image: postgres:alpine
        container_name: gitea-chitragupta
        restart: always
        volumes:
            - /trayimurti/containers/volumes/gitea/db:/var/lib/postgresql/data:Z
        environment:
            - POSTGRES_USER=gitea
            - POSTGRES_PASSWORD=/run/secrets/gitea_database_user_password
            - POSTGRES_DB=gitea
            - TZ=Asia/Kolkata
        secrets:
            - gitea_database_user_password

    thefossguy-blog:
        image: klakegg/hugo:alpine
        container_name: hugo-vaikunthnatham
        restart: always
        command: server
        ports:
            - 8020:1313
        volumes:
            - /trayimurti/containers/volumes/thefossguy-blog:/src:Z
        environment:
            - TZ=Asia/Kolkata

    nextcloud-web:
        image: nextcloud
        container_name: nextcloud-govinda
        restart: always
        ports:
            - 8010:80
        volumes:
            - /trayimurti/containers/volumes/nextcloud/root:/var/www/html:Z
        environment:
            - MYSQL_PASSWORD=/run/secrets/nextcloud_database_user_password
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
            - MYSQL_HOST=db
            - NEXTCLOUD_TRUSTED_DOMAINS=cloud.thefossguy.com bluefeds.lan 10.0.0.19
            - TZ=Asia/Kolkata
        depends_on:
            - nextcloud-db
        secrets:
            - nextcloud_database_user_password

    nextcloud-db:
        image: mariadb
        container_name: nextcloud-chitragupta
        restart: always
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        volumes:
            - /trayimurti/containers/volumes/nextcloud/db:/var/lib/mysql:Z
        environment:
            - MYSQL_ROOT_PASSWORD=/run/secrets/nextcloud_database_root_password
            - MYSQL_PASSWORD=/run/secrets/nextcloud_database_user_password
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
            - TZ=Asia/Kolkata
        secrets:
            - nextcloud_database_root_password
            - nextcloud_database_user_password

    thefossguy-mach:
        image: klakegg/hugo:alpine
        container_name: hugo-mahayogi
        restart: always
        command: server
        ports:
            - 8040:1313
        volumes:
            - /trayimurti/containers/volumes/thefossguy-machines:/src:Z
        environment:
            - TZ=Asia/Kolkata

# sudo firewall-cmd --permanent --add-port=8080/tcp --add-port=8443/tcp --add-port= --add-port= --add-port= --add-port= --add-port= --add-port= --add-port= --add-port= 
# sudo firewall-cmd --reload
# sudo firewall-cmd --list-ports
