version: 2.1

services:
    netbootxyz:
        image: lscr.io/linuxserver/netbootxyz:latest
        container_name: netbootxyz
        restart: unless-stopped
        ports:
            - 3000:3000
            - 69:69/udp
            - 8080:80 #optional
        environment:
            - PUID=1000
            - PGID=1000
            - MENU_VERSION=1.9.9 #optional
            - PORT_RANGE=30000:30010 #optional
            - SUBFOLDER=/ #optional
        volumes:
            - /path/to/config:/config
            - /path/to/assets:/assets #optional
