version: 3.7

services:

  reverse-proxy:
    image: caddy:alpine
    container_name: caddy-vishwambhar
    command: caddy run --config /etc/caddy/Caddyfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/container-volumes/caddy/Caddyfile:/etc/caddy/Caddyfile:Z
      - ~/container-volumes/caddy/site:/srv:Z
      - ~/container-volumes/caddy/caddy_data:/data:Z
      - ~/container-volumes/caddy/caddy_config:/config:Z
      - ~/container-volumes/caddy/ssl:/etc/ssl:Z
    depends_on:
      - ghost-web
      - nextcloud-web

  ghost-web:
    image: ghost:alpine
    container_name: ghost-govinda
    restart: always
    ports:
      - "8080:2368"
    volumes:
      - ~/container-volumes/ghost:/var/lib/ghost/content:z
    environment:
      - url=https://rustbytes.com
      - database__client=mysql
      - database__connection__host=ghost-db
      - database__connection__user=root
      - database__connection__password=/run/secrets/ghost_database_root_password
      - database__connection__database=ghost
      - mail__transport=SMTP
      - mail__options__host=
      - mail__options__port=
      - mail__options__secureConnection=true
      - mail__options__auth__user=
      - mail__options__auth__pass=
      - mail__from=# (want to use something like "Team Rust Bytes <admin@rustbytes.com>" ?)
      - NODE_ENV=production
    secrets:
      - ghost_database_root_password
    depends_on:
      - ghost-db

  ghost-db:
    image: mysql:8.0
    container_name: mysql-chitragupta
    restart: always
    volumes:
      - ~/container-volumes/mysql:/var/lib/mysql:z
    environment:
      - MYSQL_ROOT_PASSWORD=/run/secrets/ghost_database_root_password
    secrets:
      - ghost_database_root_password

secrets:
  ghost_database_root_password:
    external: true
