version: "2.1"

services:
    syncthing:
        image: lscr.io/linuxserver/syncthing:latest
        container_name: syncthing-vishwakarma
        hostname: untrusted_sentinel
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Kolkata
        volumes:
            - /trayimurti/containers/volumes/syncthing/config:/config
            - /trayimurti/containers/volumes/syncthing/data:/data
        ports:
            - 8001:8384
            - 22000:22000/tcp
            - 22000:22000/udp
            - 21027:21027/udp
        restart: unless-stopped
        security_opt:
            - label=disable

# create dirs
# mkdir -p /trayimurti/containers/volumes/syncthing/{config,data}
