version: 3.3

services:

    reverse-proxy:
        image: caddy:2-alpine
        container_name: caddy-vishveshwaraya
        command: caddy run --config /etc/caddy/Caddyfile
        restart: always
        ports:
            - 8008:80
            - 8443:443
        volumes:
            - /trayimurti/containers/volumes/caddy/Caddyfile:/etc/caddy/Caddyfile:Z
            - /trayimurti/containers/volumes/caddy/site:/srv:Z
            - /trayimurti/containers/volumes/caddy/caddy_data:/data:Z
            - /trayimurti/containers/volumes/caddy/caddy_config:/config:Z
            - /trayimurti/containers/volumes/caddy/ssl:/etc/ssl:Z

# mkdir -vp /trayimurti/containers/volumes/caddy/{site,ssl,caddy_{data,config}}
