version: 3

services:
    server:
        image: klakegg/hugo:alpine
        container_name: hugo-thefossguy-machines-mahayogi
        restart: always
        command: server
        ports:
            - 8040:1313
        volumes:
            - /trayimurti/containers/volumes/thefossguy-machines:/src:Z
        environment:
            - TZ=Asia/Kolkata

# this image is not official, but is endorsed in a somewhat official capacity
# https://discourse.gohugo.io/t/klakeggs-wonderful-hugo-docker-image-update-thread/20347
# https://gohugo.io/getting-started/installing/#docker
