version: 3

services:
    db:
        image: mariadb
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        restart: always
        volumes:
            - db:/var/lib/mysql:Z
        environment:
            - MYSQL_ROOT_PASSWORD=
#        env_file:
#            - db.env

    redis:
        image: redis:alpine
        restart: always

    app:
        image: nextcloud:fpm-alpine
        restart: always
        volumes:
            - nextcloud:/var/www/html:Z
        environment:
            - MYSQL_HOST=db
            - REDIS_HOST=redis
#        env_file:
#            - db.env
        depends_on:
            - db
            - redis

    web:
        build: ./web
        restart: always
        volumes:
            - nextcloud:/var/www/html:ro
        environment:
            - VIRTUAL_HOST=
            - LETSENCRYPT_HOST=
            - LETSENCRYPT_EMAIL=
        depends_on:
            - app

    cron:
        image: nextcloud:fpm-alpine
        restart: always
        volumes:
            - nextcloud:/var/www/html:Z
        entrypoint: /cron.sh
        depends_on:
            - db
            - redis

    proxy:
        build: ./proxy
        restart: always
        ports:
            - 80:80
            - 443:443
        labels:
            com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
        volumes:
            - certs:/etc/nginx/certs:ro
            - vhost.d:/etc/nginx/vhost.d:Z
            - html:/usr/share/nginx/html:Z
            - /var/run/docker.sock:/tmp/docker.sock:ro

    letsencrypt-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        volumes:
            - certs:/etc/nginx/certs:Z
            - vhost.d:/etc/nginx/vhost.d:Z
            - html:/usr/share/nginx/html:Z
            - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
            - proxy
