version: 3.3

services:
    db:
        image: mariadb
        container_name: nextcloud-chitragupta
        restart: always
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        volumes:
            - /trayimurti/containers/volumes/nextcloud/db:/var/lib/mysql:Z
        environment:
            - MYSQL_ROOT_PASSWORD=/run/secrets/nextcloud_database_root_password
            - MYSQL_PASSWORD=/run/secrets/nextcloud_database_user_password
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
            - TZ=Asia/Kolkata
        secrets:
            - nextcloud_database_root_password
            - nextcloud_database_user_password

    app:
        image: nextcloud
        container_name: nextcloud-govinda
        restart: always
        ports:
            - 8010:80
        depends_on:
            - db
        volumes:
            - /trayimurti/containers/volumes/nextcloud/root:/var/www/html:Z
        environment:
            - MYSQL_PASSWORD=/run/secrets/nextcloud_database_user_password
            - MYSQL_DATABASE=nextcloud
            - MYSQL_USER=nextcloud
            - MYSQL_HOST=db
#            - NEXTCLOUD_TRUSTED_DOMAINS=cloud.thefossguy.com bluefeds.lan 10.0.0.19
            - TZ=Asia/Kolkata
        secrets:
            - nextcloud_database_user_password

secrets:
    nextcloud_database_root_password:
        external: true
    nextcloud_database_user_password:
        external: true

# create dirs
# mkdir -vp /trayimurti/containers/volumes/nextcloud/{db,root}

# create secrets
# openssl rand -base64 20 | podman secret create nextcloud_database_root_password -
# openssl rand -base64 20 | podman secret create nextcloud_database_user_password -
